### ISSUE TITLE
Design thoughts

### ISSUE THREAD

**Issue by elazar** [sparkphp/auth#1]
I think the current `AbstractAuthenticator` implementation may be trying to fulfill too many concerns, at least for a default implementation. Currently, it:

1. extracts a token from a request;
2. maintains accessors for the token;
3. maintains accessors for the error code and message;
4. maintains accessors for permissions.

The way in which 1 is done may vary depending on the authentication scheme in use, so I think it makes sense to leave this responsibility with the authenticator.

I'm not sure 2 is necessary, at least not for our use case. We should be able to have Auryn fetch the token instance from the authenticator once per request -- and that should happen on each request -- and return the same instance for subsequent reads.

3 can be handled outside the authenticator. One approach to that would be returning a response object that includes either the token or error information with appropriately semantic accessors. Another would be to either have a token object returned or throw a normalized exception or set of exceptions for failures.

4 seems like unclean separation of concerns as well, because it's combining authentication (identifying the user) and authorization (based on authentication, what operations the user has access to). If this remains, we may want to consider moving authorization-related functionality to a separate interface that each authenticator can implement or not depending on availability of support and need for that functionality.

I'd like to see us have an `AuthenticatorInterface` interface that defines a minimal implementation. Given my comments above, I think that is limited to concern 1 above. Here's one possible implementation:

```php
// src/AuthenticatorInterface.php
interface AuthenticatorInterface
{
    /**
     * @param \Psr\Http\Message\RequestInterface $request
     * @return \Spark\Auth\Token
     */
    public function authenticate(RequestInterface $request);
}

// src/Token.php
class Token
{
    /**
     * @var string
     */
    protected $token;

    /**
     * @var array
     */
    protected $metadata;

    /**
     * @param string $token
     * @param array $metadata
     */
    public function __construct($token, array $metadata)
    {
         $this->token = $token;
         $this->metadata = $metadata;
    }

    /**
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @param string|null $key
     * @return mixed
     */
    public function getMetadata($key = null)
    {
        if ($key !== null) {
             return isset($this->metadata[$key]) ? $this->metadata[$key] : null;
        }
        return $this->metadata;
    }
}
```

**Comment by dolfelt** [comment]
I think a lot of those concerns are valid. We can definitely break out the `Token` into it's own class. What I would like to see remain in the authenticator class is status on where in the process it is. Ideally being able to check if there is no authentication, failed auth, or passed auth. That makes it extremely easy down the chain to validate your authentication.

I understand we want to do minimal work here, but I really want to keep sane defaults so there isn't a huge amount of effort to use it out of the box. (i.e. storing your token elsewhere and trying to figure out if the request is authenticated)

**Comment by elazar** [comment]
Agreed, I'd rather have something that can work out of the box. That's actually another reason I bring all of this up: I think we should build at least one authenticator implementation to dog food this library, probably one that authenticates against WIW using the PHP client library for it.

I'm inclined to say let's use exceptions to indicate failure, with a base namespace of `Spark\Auth\Exception` and a base class of `GeneralException` that's then extended by `NoAuthException`, `FailedAuthException`, and any other cases we find we need. We can just have `authenticate()`, or whatever we choose to name it, return a token instance on success.

**Comment by dolfelt** [comment]
Sounds like a plan. Let me know what you want from me.
